io_table_physicalunits_path = "io_tables/io_table_physicalunits.csv"
energy_content_path = "unit_conversions_and_mw/energy_content_by_mass_and_volume.csv"
fuel_aliases_path = "unit_conversions_and_mw/fuel_aliases.csv"
co2_filepath = "io_tables/impact_vectors/co2_impact.csv"
ch4_filepath = "io_tables/impact_vectors/ch4_impact.csv"
n2o_filepath = "io_tables/impact_vectors/n2o_impact.csv"
water_consumption_path = "io_tables/impact_vectors_water/water_consumption.csv"
water_withdrawal_path = "io_tables/impact_vectors_water/water_withdrawal.csv"
